# Generated by Django 5.2.7 on 2026-05-12 12:04

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorieEmploye',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='Inconnu', max_length=100)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Categorie Employe',
                'verbose_name_plural': 'Categories Employes',
            },
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='Inconnu', max_length=100, unique=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Destination',
                'verbose_name_plural': 'Destinations',
            },
        ),
        migrations.CreateModel(
            name='Entite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='Inconnu', max_length=100, unique=True)),
                ('abreviation', models.CharField(blank=True, max_length=4, null=True)),
            ],
            options={
                'verbose_name': 'Entite',
                'verbose_name_plural': 'Entites',
            },
        ),
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='Inconnu', max_length=100, unique=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Profil',
                'verbose_name_plural': 'Profils',
            },
        ),
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('filiale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.entite')),
            ],
            options={
                'verbose_name': 'Direction',
                'verbose_name_plural': 'Directions',
                'ordering': ['nom'],
                'unique_together': {('nom', 'filiale')},
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('matricule', models.CharField(default='Inconnu', max_length=20, unique=True)),
                ('fonction', models.CharField(default='Inconnu', max_length=100)),
                ('date_naissance', models.DateField(default='1900-01-01')),
                ('telephone', models.CharField(default='Inconnu', max_length=20, unique=True)),
                ('email_reciever', models.EmailField(blank=True, default='Inconnu', max_length=254, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.categorieemploye')),
                ('direction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.direction')),
                ('filiale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.entite')),
                ('profil', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.profil')),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_demande', models.DateField()),
                ('objet_mission', models.CharField(max_length=255)),
                ('date_depart', models.DateField()),
                ('date_retour', models.DateField()),
                ('lieu_mission', models.CharField(max_length=255)),
                ('statut_mission', models.CharField(choices=[('EN_COURS', 'En cours'), ('APPROUVEE', 'Approuvée'), ('REJETEE', 'Rejetée'), ('TERMINEE', 'Terminée')], default='EN_ATTENTE', max_length=20)),
                ('numero_mission', models.CharField(max_length=100, unique=True)),
                ('contexte_mission', models.TextField(blank=True, null=True)),
                ('objectifs_mission', models.TextField(blank=True, null=True)),
                ('frais_extra', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('demandeur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('destination_mission', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.destination')),
                ('entite', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.entite')),
            ],
            options={
                'verbose_name': 'Mission',
                'verbose_name_plural': 'Missions',
                'db_table': 'missions',
                'ordering': ['-date_demande'],
            },
        ),
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_etape', models.PositiveIntegerField()),
                ('libelle_etape', models.CharField(max_length=255)),
                ('filiale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.entite')),
            ],
            options={
                'verbose_name': 'Workflow',
                'verbose_name_plural': 'Workflows',
                'db_table': 'workflows',
                'ordering': ['filiale', 'numero_etape'],
                'unique_together': {('filiale', 'numero_etape')},
            },
        ),
        migrations.CreateModel(
            name='Bareme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hebergement', models.PositiveIntegerField(default=0)),
                ('perdiem', models.PositiveIntegerField(default=0)),
                ('communication', models.PositiveIntegerField(default=0)),
                ('transport', models.PositiveIntegerField(default=0)),
                ('forfait', models.PositiveIntegerField(default=0)),
                ('longue_duree', models.PositiveIntegerField(default=0)),
                ('categorie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.categorieemploye')),
                ('destination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.destination')),
                ('filiale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.entite')),
            ],
            options={
                'verbose_name': 'Indemnité de mission',
                'verbose_name_plural': 'Indemnités de mission',
                'ordering': ['categorie', 'destination'],
                'unique_together': {('categorie', 'destination')},
            },
        ),
        migrations.CreateModel(
            name='UserWorkflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflows', to=settings.AUTH_USER_MODEL)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.workflow')),
            ],
            options={
                'verbose_name': 'Utilisateur Workflow',
                'verbose_name_plural': 'Utilisateurs Workflow',
                'db_table': 'user_workflows',
                'unique_together': {('workflow', 'user')},
            },
        ),
        migrations.CreateModel(
            name='MissionWorkflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('statut', models.BooleanField(blank=True, null=True)),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapes_workflow', to='api.mission')),
                ('user_validation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validations_mission', to=settings.AUTH_USER_MODEL)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapes_mission', to='api.workflow')),
            ],
            options={
                'verbose_name': 'Étape de validation de mission',
                'verbose_name_plural': 'Étapes de validation des missions',
                'db_table': 'missions_workflow',
                'ordering': ['mission'],
                'unique_together': {('mission', 'workflow')},
            },
        ),
    ]
