# Generated by Django 5.2.7 on 2026-05-12 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bareme',
            unique_together={('filiale', 'categorie', 'destination')},
        ),
    ]
