# Generated by Django 5.2.7 on 2026-05-12 15:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_bareme_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='etapes_workflow', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='UserWorkflow',
        ),
    ]
