# Generated by Django 5.2.7 on 2026-05-12 15:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_workflow_user_delete_userworkflow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='demandeur',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mission',
            name='destination_mission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.destination'),
        ),
        migrations.AlterField(
            model_name='mission',
            name='entite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.entite'),
        ),
        migrations.AlterField(
            model_name='mission',
            name='numero_mission',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='mission',
            name='statut_mission',
            field=models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('EN_COURS', 'En cours'), ('APPROUVEE', 'Approuvée'), ('REJETEE', 'Rejetée'), ('TERMINEE', 'Terminée')], default='EN_ATTENTE', max_length=20),
        ),
    ]
