# Generated by Django 5.2.7 on 2026-05-12 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_mission_demandeur_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='missionworkflow',
            options={'ordering': ['mission', 'workflow__numero_etape'], 'verbose_name': 'Étape de validation de mission', 'verbose_name_plural': 'Étapes de validation des missions'},
        ),
        migrations.AlterField(
            model_name='missionworkflow',
            name='statut',
            field=models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('APPROUVE', 'Approuvé'), ('REJETE', 'Rejeté')], default='EN_ATTENTE', max_length=20),
        ),
    ]
