# Generated by Django 5.2.7 on 2026-05-15 12:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_missionworkflow_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delegation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('est_chef', models.BooleanField(default=False)),
                ('montant_hebergement_justifie', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('hebergement_justifie', models.BooleanField(default=False)),
                ('perdiem_recu', models.BooleanField(default=False)),
                ('bareme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.bareme')),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delegations', to=settings.AUTH_USER_MODEL)),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delegations', to='api.mission')),
            ],
            options={
                'verbose_name': 'Membre de délégation',
                'verbose_name_plural': 'Membres de délégation',
                'unique_together': {('mission', 'employe')},
            },
        ),
    ]
