# Generated by Django 5.2.7 on 2026-05-15 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_delegation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delegation',
            name='hebergement_justifie',
        ),
        migrations.RemoveField(
            model_name='delegation',
            name='montant_hebergement_justifie',
        ),
        migrations.RemoveField(
            model_name='delegation',
            name='perdiem_recu',
        ),
    ]
