# Generated by Django 5.2.7 on 2026-05-15 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_delegation_hebergement_justifie_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='delegation',
            name='duree',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='delegation',
            name='est_longue_duree',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='delegation',
            name='montant_communication',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='delegation',
            name='montant_hebergement',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='delegation',
            name='montant_perdiem',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='delegation',
            name='montant_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='delegation',
            name='montant_transport',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
