# Generated by Django 5.2.7 on 2026-05-15 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_delegation_duree_delegation_est_longue_duree_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('CHEQUE', 'Chèque'), ('LIQUIDE', 'Liquide')], max_length=10)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reference_cheque', models.CharField(blank=True, max_length=100, null=True)),
                ('date_paiement', models.DateField()),
                ('effectue', models.BooleanField(default=False)),
                ('delegation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='paiement', to='api.delegation')),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
            },
        ),
    ]
