# Generated by Django 5.2.7 on 2026-05-18 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_paiement'),
    ]

    operations = [
        migrations.CreateModel(
            name='JustificationHebergement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_soumission', models.DateTimeField(auto_now_add=True)),
                ('delegation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='justification_hebergement', to='api.delegation')),
            ],
            options={
                'verbose_name': 'Justification hébergement',
                'verbose_name_plural': 'Justifications hébergement',
            },
        ),
        migrations.CreateModel(
            name='PieceJustificative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=255)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('document', models.FileField(upload_to='justifications/%Y/%m/')),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('justification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pieces', to='api.justificationhebergement')),
            ],
            options={
                'verbose_name': 'Pièce justificative',
                'verbose_name_plural': 'Pièces justificatives',
                'ordering': ['date_ajout'],
            },
        ),
    ]
