# Generated by Django 5.2.7 on 2026-05-26 20:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_validation_comptable_mission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mission',
            name='date_validation_comptable',
        ),
        migrations.RemoveField(
            model_name='mission',
            name='valide_par_comptable',
        ),
        migrations.AddField(
            model_name='justificationhebergement',
            name='date_validation_comptable',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='justificationhebergement',
            name='valide_par_comptable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='justifications_validees', to=settings.AUTH_USER_MODEL),
        ),
    ]
