# Generated by Django 5.2.7 on 2026-08-22 10:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_paiement_cheque_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordSetupToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('motif', models.CharField(choices=[('CREATION', 'Création de compte'), ('REINITIALISATION', 'Réinitialisation')], default='CREATION', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_setup_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lien de définition de mot de passe',
                'verbose_name_plural': 'Liens de définition de mot de passe',
                'ordering': ['-created_at'],
            },
        ),
    ]
