# Generated by Django 5.2.7 on 2026-08-26 09:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_alter_user_telephone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bareme',
            name='categorie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.categorieemploye'),
        ),
        migrations.AlterField(
            model_name='bareme',
            name='destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.destination'),
        ),
        migrations.AlterField(
            model_name='bareme',
            name='filiale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.entite'),
        ),
        migrations.AlterField(
            model_name='delegation',
            name='employe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delegations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='direction',
            name='filiale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.entite'),
        ),
        migrations.AlterField(
            model_name='mission',
            name='demandeur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mission',
            name='destination_mission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.destination'),
        ),
        migrations.AlterField(
            model_name='mission',
            name='entite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.entite'),
        ),
        migrations.AlterField(
            model_name='user',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.categorieemploye'),
        ),
        migrations.AlterField(
            model_name='user',
            name='direction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.direction'),
        ),
        migrations.AlterField(
            model_name='user',
            name='filiale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.entite'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.profil'),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='filiale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.entite'),
        ),
    ]
