# Generated by Django 5.2.7 on 2026-08-28 09:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_alter_bareme_categorie_alter_bareme_destination_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='missionworkflow',
            name='traite_par',
            field=models.ForeignKey(blank=True, help_text='Qui a réellement agi — peut différer du signataire désigné.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='etapes_traitees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Suppleance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateTimeField()),
                ('date_fin', models.DateTimeField()),
                ('motif', models.CharField(blank=True, max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suppleances_creees', to=settings.AUTH_USER_MODEL)),
                ('filiale', models.ForeignKey(blank=True, help_text='Restreint la suppléance à cette filiale. Vide = toutes.', null=True, on_delete=django.db.models.deletion.PROTECT, to='api.entite')),
                ('suppleant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suppleances_recues', to=settings.AUTH_USER_MODEL)),
                ('titulaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suppleances_accordees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Suppléance de signature',
                'verbose_name_plural': 'Suppléances de signature',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.AddField(
            model_name='missionworkflow',
            name='suppleance',
            field=models.ForeignKey(blank=True, help_text="Renseigné si l'étape a été traitée au titre d'une suppléance.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='etapes_traitees', to='api.suppleance'),
        ),
        migrations.AddIndex(
            model_name='suppleance',
            index=models.Index(fields=['titulaire', 'active', 'date_debut', 'date_fin'], name='api_supplea_titulai_3ab8ed_idx'),
        ),
    ]
