# Generated by Django 5.2.7 on 2026-08-28 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_missionworkflow_traite_par_suppleance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suppleance',
            name='filiale',
        ),
    ]
